version: '3'

volumes: 
  loki-data:
    driver: local

services:
  loki:
    image: grafana/loki:latest
    ports:
      - "3331:3100"
    # command: -config.file=/etc/loki/local-config.yaml
    volumes:
      # - ./loki-config.yaml:/etc/loki/local-config.yaml
      - loki-data:/loki

  
