version: '3.8'

services:
  snmp_exporter:
    image: prom/snmp-exporter
    container_name: snmp_exporter
    restart: unless-stopped
    command:
      - '--config.file=/etc/snmp_exporter/snmp.yml'
      - '--web.listen-address=:9116'
    volumes:
      - ./snmp.yml:/etc/snmp_exporter/snmp.yml
    ports:
      - 9116:9116

