version: '3'

services:
    db: 
      image: mysql:latest
      container_name: mysql
      restart: always
      ports:
        - 3306:3306
      environment: 
        MYSQL_ROOT_PASSWORD: mysqlDocker
      volumes:
        - mysql:/var/lib/mysql
      networks:
        - earth

    # adminer:
    #   image: adminer
    #   restart: always
    #   ports: 
    #     - 8080:8080

networks:
  earth:
    external: true
    name: earth

volumes:
  mysql:
    external: true
    name:
      mysql